[compat]
julia = "1.5.1"
[deps]
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
CSV = "0.8.2"
Distributions = "0.23.8"
GaussianProcesses = "0.12.3"
Plots = "1.0.14"
ProfileVega = "1.1.0"
Soss = "0.16.2"
StatsPlots="0.14.17"
Stheno = "0.6.17"
Turing = "0.15.8"